Error del forms solucionado, nuevo error
*Al hacer login
Exception has occurred. _ClientSocketException (Connection reset by peer)

*Al hacer registro
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method '[ ]' was called on null.
Receiver: null
Tried calling: [ ]("message"))